### PR TITLE
GPII-3190: Initial review for wider reuse.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [https://issues.gpii.net/browse/GPII-3190](https://issues.gpii.net/browse/GPII-3190) for details.

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
@sgithens, this pull references a branch that you can safely work with, which has been tested with modern infusion.

**Comment by sgithens** [comment]
@the-t-in-rtf Thanks Tony!  Cloning your branch now to try it out!

**Comment by the-t-in-rtf** [comment]
@amb26, how do you want to work the review of the new features Steve has submitted [in the pull against this branch](https://github.com/the-t-in-rtf/gpii-express-user/pull/7)?

**Comment by amb26** [comment]
I guess it can work through its review in place for the time being since there are a lot of comments in progress on that pull - but in time it would be good for it to become regenerated as a pull against master together with a link to its old location

**Pull request merged**
